# Generated by Django 3.1.2 on 2020-11-01 23:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=150, verbose_name='firstname')),
                ('last_name', models.CharField(max_length=300, verbose_name='lastname')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='mobilenumber')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('superuser', models.BooleanField(default=False, verbose_name='وضعیت مدیریت')),
                ('staff', models.BooleanField(default=False, verbose_name='وضعیت کارمندی')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تارخ تولد')),
                ('profile', models.ImageField(default='static/img/joblogo.png', upload_to='media/images/profile/', verbose_name='عکس پروفایل')),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, 'انتخاب جنسیت'), (1, 'زن'), (2, 'مرد'), (3, 'سایر')], default=0, verbose_name='جنسیت')),
                ('address', models.JSONField(blank=True, null=True, verbose_name='آدرس')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('factors_list', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None, verbose_name='لیست فاکتور های کاربر')),
                ('saved_products_list', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None, verbose_name='محصولات ذخیره شده')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OptionMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('content', models.JSONField(verbose_name='محتوا')),
            ],
            options={
                'verbose_name': 'آپشن',
                'verbose_name_plural': 'آپشن ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image_list', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='لیست عکس های محصول')),
                ('point', models.FloatField(default=0.0, verbose_name='امتیاز')),
                ('price', models.CharField(max_length=15, verbose_name='قیمت')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='درصد تخفیف محصول')),
                ('inventory', models.PositiveSmallIntegerField(default=0, verbose_name='موجودی محصول')),
                ('attributes', models.JSONField(blank=True, null=True, verbose_name='لیست ویژگی ها')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'عدم انتشار')], default=False, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='media/images/slider/', verbose_name='عکس')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('dtatupdate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
                'ordering': ('id',),
            },
        ),
    ]
