# Generated by Django 3.1.2 on 2020-11-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201102_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='موجودی محصول'),
        ),
    ]
