# Generated by Django 3.1.2 on 2020-11-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_slider_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('valid_code', models.CharField(max_length=6, null=True, verbose_name='کد فعال سازی')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
