# Generated by Django 3.1.2 on 2020-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(verbose_name='شناسه')),
                ('summary', models.CharField(max_length=300, verbose_name='خلاصه')),
                ('code', models.TextField(verbose_name='کد HTML')),
                ('top_image', models.ImageField(upload_to='media/images/blog/', verbose_name='عکس شاخص')),
                ('slider', models.ImageField(upload_to='media/images/blog/slider/', verbose_name='اسلایدر')),
                ('reted_list', models.JSONField(blank=True, null=True, verbose_name='لیست امتیاز')),
                ('liked_list', models.JSONField(blank=True, null=True, verbose_name='لیست لایک')),
                ('datecreate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
                ('dtatupdate', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('publish', models.BooleanField(choices=[(True, 'منتشر شده'), (False, 'منتشر نشده')], default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
                'ordering': ('id',),
            },
        ),
    ]
