# Generated by Django 3.1.2 on 2020-11-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='top_image',
            field=models.URLField(null=True, verbose_name='عکس شاخص'),
        ),
    ]
