# Generated by Django 3.1.2 on 2020-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201104_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='url',
        ),
        migrations.AddField(
            model_name='slider',
            name='position',
            field=models.CharField(choices=[('0', 'اسلایدر-صفحه اصلی'), ('1', 'بنر-وسط صفحه اصلی'), ('2', 'اسلایدر-صفحه درباره ما'), ('3', 'بنر-درباره ما')], default='0', max_length=1, verbose_name='موقعیت مکانی'),
        ),
    ]
