# Generated by Django 3.1.2 on 2020-11-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201109_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
