# Generated by Django 3.1.2 on 2020-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.CharField(choices=[('0', 'اسلایدر-صفحه اصلی'), ('1', 'بنر-وسط صفحه اصلی'), ('2', 'اسلایدر-صفحه درباره ما'), ('3', 'بنر-درباره ما'), ('4', 'اسلایدر- صفحه بلاگ')], default='0', max_length=1, verbose_name='موقعیت مکانی'),
        ),
    ]
