# Generated by Django 3.1.2 on 2020-11-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201115_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='موبایل')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('0', 'خوانده نشده'), ('1', 'در حال بررسی'), ('2', 'بررسی شده')], default='0', max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط های با ما',
                'ordering': ('id',),
            },
        ),
    ]
