# Generated by Django 3.1.2 on 2020-12-21 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCount', models.PositiveIntegerField(default=1, verbose_name='تعداد محصول')),
                ('FK_Product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Factor_Product', to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'محصول فاکتور',
                'verbose_name_plural': 'محصول فاکتور ها',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.CharField(blank=True, max_length=11, verbose_name='شماره موبایل')),
                ('ZipCode', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('Address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('City', models.CharField(blank=True, max_length=50, verbose_name='شهر')),
                ('BigCity', models.CharField(blank=True, max_length=50, verbose_name='شهرستان')),
                ('State', models.CharField(blank=True, max_length=50, verbose_name='استان')),
                ('TotalPrice', models.CharField(max_length=15, verbose_name='هزینه کل')),
                ('PaymentStatus', models.BooleanField(choices=[(True, 'پرداخت شد'), (False, 'پرداخت نشده')], default=False, verbose_name='وضعیت پرداخت')),
                ('OrderDate', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('OrderStatus', models.CharField(choices=[('0', 'سفارش تحویل داده شده است'), ('1', 'سفارش آماده است'), ('2', 'سفارش در حال آماده سازی است'), ('3', 'منتظر بررسی'), ('4', 'سفارش لغو شده است'), ('5', 'سفارش ارسال شده است')], default='3', max_length=1, verbose_name='وضعیت سفارش')),
                ('FK_FactorPost', models.ManyToManyField(blank=True, related_name='Factor_Products', to='shop.FactorPost', verbose_name='محصولات فاکتور')),
                ('FK_User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='UserFactor', to=settings.AUTH_USER_MODEL, verbose_name='صاحب فاکتور')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
                'ordering': ('id',),
            },
        ),
    ]
