# Generated by Django 3.1.2 on 2020-12-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_factor_factorpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorpost',
            name='Endprice',
            field=models.BigIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
