# Generated by Django 3.1.2 on 2021-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_factorpost_endprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='static/img/default-profile.jpg', upload_to='media/images/profile/', verbose_name='عکس پروفایل'),
        ),
    ]
