name: Mouse-Keyboard-Store
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: update-liara

        run: |
          npm i -g @liara/cli@2
          liara login --region iran --email moeintaheri.1998@gmail.com --password narjes81475177@taheri 
          liara deploy --detach